In [1]:
class Employee:
    # Class variable to count the number of Employees
    employee_count = 0
    
    def __init__(self, name, family, salary, department):
        """Initialize an employee instance."""
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        # Incrementing the employee count
        Employee.employee_count += 1
    
    def display_employee_info(self):
        """Display information about the employee."""
        print(f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}")

    @classmethod
    def average_salary(cls, employees):
        """Calculate the average salary for a list of employees."""
        total_salary = sum(emp.salary for emp in employees)
        return total_salary / len(employees) if employees else 0


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department):
        """Initialize a full-time employee instance."""
        # Call the constructor of the parent class (Employee)
        super().__init__(name, family, salary, department)


# Creating instances of Employee class
employee1 = Employee("Amit Joshi", "Joshi Family", 45000, "IT")
employee2 = Employee("Sanjay Sahu", "Sahu Family", 55000, "HR")

# Creating instances of FulltimeEmployee class
fulltime_employee1 = FulltimeEmployee("Amit Trivedi", "Trivedi Family", 65000, "Finance")
fulltime_employee2 = FulltimeEmployee("Ranbir Kapoor", "Kapoor Family", 80000, "Marketing")

# Displaying employee information
employee1.display_employee_info()
employee2.display_employee_info()

fulltime_employee1.display_employee_info()
fulltime_employee2.display_employee_info()

# Displaying average salary
employees_list = [employee1, employee2, fulltime_employee1, fulltime_employee2]
average_salary = Employee.average_salary(employees_list)
print(f"\nAverage Salary: {average_salary}")


Name: Amit Joshi, Family: Joshi Family, Salary: 45000, Department: IT
Name: Sanjay Sahu, Family: Sahu Family, Salary: 55000, Department: HR
Name: Amit Trivedi, Family: Trivedi Family, Salary: 65000, Department: Finance
Name: Ranbir Kapoor, Family: Kapoor Family, Salary: 80000, Department: Marketing

Average Salary: 61250.0


In [2]:
import numpy as np

# Create random vector of size 20
x = np.random.uniform(1, 20, 20)  

print("Original Vector:")
print(x)

# Reshape to 4 by 5 
x = x.reshape(4, 5)   

print("Reshaped Array:")
print(x) 

# Replace max in each row by 0
row_max = x.max(axis=1, keepdims=True)  
x[x == row_max] = 0

print("Replaced max in each row by 0:") 
print(x)

Original Vector:
[13.66488847 15.63221612  4.33167872  3.3406158   8.32463566 19.09720329
 13.16193043  9.59443682  8.1146182   7.98125422 14.89937616  7.72422714
 17.1871123   1.19390712  4.04821639  2.61678227 10.18742661 12.90404384
  7.61645135  5.52357445]
Reshaped Array:
[[13.66488847 15.63221612  4.33167872  3.3406158   8.32463566]
 [19.09720329 13.16193043  9.59443682  8.1146182   7.98125422]
 [14.89937616  7.72422714 17.1871123   1.19390712  4.04821639]
 [ 2.61678227 10.18742661 12.90404384  7.61645135  5.52357445]]
Replaced max in each row by 0:
[[13.66488847  0.          4.33167872  3.3406158   8.32463566]
 [ 0.         13.16193043  9.59443682  8.1146182   7.98125422]
 [14.89937616  7.72422714  0.          1.19390712  4.04821639]
 [ 2.61678227 10.18742661  0.          7.61645135  5.52357445]]
